/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f4f4f2",
        "secondary": "#755b00",
        "surface-variant": "#e2e3e1",
        "on-tertiary-fixed-variant": "#474746",
        "on-background": "#1a1c1b",
        "surface-tint": "#4f5e81",
        "outline": "#75777f",
        "on-primary": "#ffffff",
        "primary": "#041534",
        "on-secondary-container": "#785d00",
        "outline-variant": "#c5c6cf",
        "surface-container-high": "#e8e8e6",
        "primary-container": "#1b2a4a",
        "on-surface-variant": "#45464e",
        "surface-container-highest": "#e2e3e1",
        "on-secondary-fixed": "#241a00",
        "inverse-on-surface": "#f1f1ef",
        "inverse-primary": "#b7c6ee",
        "primary-fixed": "#d9e2ff",
        "surface-container": "#eeeeec",
        "primary-fixed-dim": "#b7c6ee",
        "on-tertiary": "#ffffff",
        "on-surface": "#1a1c1b",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e6c364",
        "tertiary-fixed-dim": "#c8c6c5",
        "background": "#f9f9f7",
        "error": "#ba1a1a",
        "tertiary-container": "#2b2b2b",
        "tertiary-fixed": "#e5e2e1",
        "secondary-container": "#fed977",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#949292",
        "on-secondary-fixed-variant": "#584400",
        "tertiary": "#171717",
        "surface-dim": "#dadad8",
        "on-primary-fixed-variant": "#384668",
        "secondary-fixed": "#ffe08f",
        "surface": "#f9f9f7",
        "inverse-surface": "#2f3130",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-bright": "#f9f9f7",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0a1a3a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8392b7"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "stack-md": "32px",
        "section-padding": "120px",
        "stack-sm": "16px",
        "stack-lg": "64px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1120px"
      },
      fontFamily: {
        "display-lg-mobile": ["Playfair Display"],
        "verse-quote": ["Noto Serif"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "headline-md": ["Playfair Display"]
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "verse-quote": ["20px", { lineHeight: "1.7", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
